"""add retry and lifecycle columns to videos

Revision ID: 030a90e4080c
Revises: d194ec194b8c
Create Date: 2026-04-05 01:11:55.711190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '030a90e4080c'
down_revision: Union[str, Sequence[str], None] = 'd194ec194b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('videos', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('videos', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('videos', sa.Column('failed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'failed_at')
    op.drop_column('videos', 'completed_at')
    op.drop_column('videos', 'started_at')
    op.drop_column('videos', 'retry_count')
    # ### end Alembic commands ###
